source/getting-started.rst
source/image.rst

I've just done a couple of minor content changes to the docs. Nothing of substance has changed but I think it reads better now.

Minor wording changes

---

source/conf.py

Minor bugfix for getting familiar with the docs setup.

Update catalystcloud docs copyright year

---

source/getting-started.rst
source/tutorials.rst

Just some minor grammar updates I noticed while working through the tutorial.

Minor grammar updates

---

.gitignore
source/tutorials.rst

I read this section and have proposed a few spelling/grammar changes.

Minor proofreading updates to keepalived tutorials.

---

source/tutorials.rst

Syntax changes to the Keepalived/VRRP tutorial, only.

Minor typographical changes to the tutorials.

---

LICENCE.md

add LICENCE.md containing cc-by-sa-4.0

---

source/tutorials.rst
source/tutorials/kubernetes-cluster-on-the-catalyst-cloud.rst

* add an example of building a Kubernetes cluster based on Ubuntu 14.04 and Kubernetes 1.1.3
Hi @donovan - if you have time, could you please review this new tutorial.
Thanks,
Piers.

Kubernetes cluster build tutorial

---

source/first-instance.rst
source/tutorials.rst
source/tutorials/bootstrapping-puppet.rst

Created a new article on how to bootstrap Puppet from Heat using cloud-init

create article on bootstrapping Puppet from Heat

---

scripts/create-vpn.sh
source/network.rst

Update VPN settings as per David Clarkes suggestions

udpate vpn setting

---

source/tutorials.rst
source/tutorials/ansible-create-x-servers-using-in-memory-inventory.rst

Explain how to use add_host to create in memory inventory and provide example scenario with associated playbook to illustrate a real world usage.

Create new tutorial for using Ansible in-memory inventory

---

source/first-instance.rst

Don't just assume that there's only one ACTIVE floating IP

In heat stack example, obtain specific floating IP address by its ID

---

source/access-control.rst
source/tutorials/deploying-highly-available-instances-with-keepalived.rst

Basic access control documentation.

Add information about Roles

---

source/access-control.rst

* compute_start_stop
* object_storage

New roles in keystone and policy files

---

source/faq.rst
source/faq/how-to-grow-a-cinder-volume.rst

Add faq section on how to grow a volume

---

source/access-control.rst

The above becomes clear pretty quickly after using the dashboard for a while, but formally noting it in the documentation seems appropriate.

Updating roles requires re-authentication.

---

source/image.rst

remove invalid flag from image-list command

---

source/tutorials.rst
source/tutorials/ansible-driven-puppet.rst

Here it is.  I'm considering including adding security groups via role/group vars, but perhaps that's for another day.

Add a new tutorial

---

source/object-storage.rst

corrected storageURL to production location
added named container to cURL example

minor corrections to storageURL and usage example

---

source/compute.rst
source/tutorials/using-packer-to-build-custom-bootable-images-on-the-catalyst-cloud.rst

update packer tutorial to include windows specific steps

update packer tutorial to include windows specific steps

---

source/cloud-orchestration.rst

- the heat default of ec2-user is annoying
- multiple private networks bust the sample

Cover getting standard default user and choosing a network.

---

source/first-instance/ansible.rst

added details for ansible cleanup playbook

added details for ansible cleanup playbook

---

source/object-storage.rst

added details on getting versioning up and running on containers.

update docs to include object versioning

---

source/object-storage.rst

switching from ceph to native swift.  Particularly around the
number of replicas.

Update object storage overview to reflect changes as a result of

---

scripts/create-first-instance.sh
scripts/delete-first-instance.sh
source/faq/cant-ssh-to-instance.rst
source/first-instance/ansible.rst
source/first-instance/command-line-cleanup.rst
source/first-instance/command-line.rst
source/first-instance/dashboard.rst
source/first-instance/heat.rst

A bunch of errata from the 2017-02-15 training session.

Training errata 201702

---

source/faq.rst

fix toctree to account for relocation of document

remove old entry from faq.rst

---

source/faq/can-i-use-s3cmd-for-object-storage.rst

indent after the seealso block

---

source/getting-started/regions.rst
source/getting-started/support.rst

Format: spacing
Content: Change of 'to' to 'with'

Small changes to spacing and grammar

---

source/getting-started/apis.rst
source/getting-started/quotas.rst

Restructuring sentences in a way that makes more sense, and which may flow better.

Style and flow

---

source/first-instance.rst
source/first-instance/overview.rst
source/getting-started/projects.rst

Consistent spelling for 'Flavor', changing some capitalization in lists, highlighting 'Tips' similarly to 'Notes', some spelling and punctuation, some changes to flow .

Changes for clarity, consistency, and style

---

source/first-instance/dashboard-windows.rst

Matched some content with the corresponding sections in dashboard.rst (Linux). Added whitespace between images and text to improve clarity and readability. The compiled text appears to be less crowded'.

Some changes for flow and consistency. Use whitespace for clarity

---

source/first-instance/bash-script.rst
source/first-instance/command-line.rst

Adding spacing. Some style changes. More "Note" highlights, as applicable. Restructuring for clarity and consistency.

Changes to improve readability. Highlight a number of noteworthy portions

---

source/first-instance/heat.rst

Style changes. Adding space for readability. Add important information to warning box. Change some spelling for consistency.

Style changes. Adding space for readability. Warning Box added.

---

source/first-instance/ansible.rst

Changes to style. Addition of space for readability. Creation of tips to highlight useful content.

Changes to style. Addition of space for readability. Creation of tips to highlight useful content.

---

source/first-instance/terraform.rst

Update of broken link. Adding space and rewording portions for flow and consistency

Update of broken link. Adding space and rewording portions for flow and consistency

---

source/object-storage.rst

Added details and examples on how to handle the uploading of large objects into Object Storage

add section on working with large objects

---

source/tutorials/deploying-highly-available-instances-with-keepalived.rst

Due to a Neutron bug, DHCP agents respond to lease renew requests from instances with a DHCPNAK message after they have been migrated between to another node. This breaks keepalived, therefore we would recommend that customers use static IPs on their keepalived instances.
This commit updates the instructions to create keepalived instances with fixed IP addresses and update existing keepalived instances to use static IP addresses.

Update instructions for deploying keepalived instances on the cloud

---

requirements.txt
source/block-storage.rst
source/contributing.rst
source/tutorials/using-packer-to-build-custom-bootable-images-on-the-catalyst-cloud.rst

upgrade sphinx and fix new sphinx warnings by converting code-block bash to console when displaying command line interactions

Compile warnings

---

source/access-control.rst
source/best-practices.rst
source/compute.rst
source/getting-started/regions.rst
source/index.rst

@chelios: Could you please review and merge? This changes were made to replace outdated HA documentation provided on https://catalyst.net.nz/content/compliance.

Best practices

---

source/tutorials/deploying-highly-available-instances-with-keepalived.rst

updated the tutorial so that it is using only the openstack command line tools. Tested full tutorial.

update tutorial to use only openstack cli commands

---

Makefile
README.md
autobuild_requirements.txt
live_compile.sh

Added a command to make editing the documentation easier, by having a live updating version of the documentation.

Added live reload option with ./live_compile.sh

---

source/_scripts/flask_app.py
source/load-balancer/layer-7.rst

Make testing scenario consistent to that used for L4 case.

update to L7 testing

---

source/tutorials/deploying-a-hpc-slurm-cluster.rst

Update for SLURM tutorial with section about using anti-affinity groups feature

Anti-affinity groups tutorial

---

source/index.rst
source/releasenotes.rst
source/releasenotes/orchestration.rst
source/tutorials/deploying-a-hpc-slurm-cluster.rst

This PR is adding a new menu section for release notes so that we can put changes logs/release notes for each services in the future.

Add release note for orchestration service

---

source/dashboard.rst
source/key-concepts/access.rst
source/sdks-and-toolkits/apis.rst
source/sdks-and-toolkits/cli/configure.rst
source/sdks-and-toolkits/cli/install.rst
source/sdks-and-toolkits/sdks.rst

On the suggestion of an end user, I have included information about the IP whitelist system in the configuration section of the documentation. I have also included info about the use of jumpboxes to access the APIs.

IP whitelist info update

---

source/first-instance/bash-script.rst
source/tutorials.rst
source/tutorials/deploying-matrixchat-on-catalyst-cloud.rst
source/tutorials/deploying-rocketchat-on-catalyst-cloud.rst

2 new tutorials,
1. Creating an instance on Catalyst Cloud and installing RocketChat with Bash and Cloud-Init
2. Installing the Matrix Synapse server using ansible.

2 New Tutorials

---

source/getting-started/access.rst
source/getting-started/admin.rst
source/getting-started/intro.rst
source/getting-started/services.rst
source/sdks-and-toolkits/cli/install.rst

I'd like to propose these content changes to the getting started tutorial. I think they're slightly less salesy, more informational, and provide more context for a first time user of a cloud computing system. Overall I think this content is more appropriate.

WIP: Basics intro change

---

source/kubernetes/clusters.rst
source/kubernetes/quickstart.rst

Hey, I made a few small tweaks to the syntax:
- Reflowed the text
- Changed technical terms emphasised with **text** to ``text``, as is convention.
- Changed section into codeblock that was just rendered as a quote.
- Changed section headers into recommended format according to their level.
- A few wording changes

K8s doc tweaks

---

newfile1.txt
source/block-storage/faq.rst
source/compute-service/best-practices.rst
source/getting-started/access.rst
source/getting-started/admin.rst
source/getting-started/intro.rst
source/getting-started/services.rst
source/image.rst

Made some changes to getting started section. 
Fixed:
- grammatical errors
- formatting
- spelling 
- some small content changes to make the reading easier

Amendments to existing documentation

---

source/sdks-and-toolkits/cli/install.rst
source/tutorials/deploying-a-hpc-slurm-cluster.rst

Slurm hpc updates

---

quick-compile.sh
source/kubernetes.rst
source/kubernetes/rolling-upgrade.rst

Added explanation of the rolling upgrade procedure.

K8s features

---

source/kubernetes/rolling-upgrade.rst

@chelios Please review and merge

Fixing a few typos and editing mistakes

---

source/dashboard.rst
source/dashboard/faq.rst

@chelios Please review and merge

Improved the dashboard section

---

source/load-balancer.rst
source/load-balancer/access-control.rst
source/load-balancer/health-monitor.rst
source/load-balancer/layer-7.rst

- added ACL via allowed CIDR
- tidied up example in L7 routing
- clarified that health check requires user implementation and example

added allowed-cidr and some minor improvements

---

source/sdks-and-toolkits/cli/configure.rst

Its a small change which should have a bigger impact for user experience by not giving outdated information.
There's definitely more improvements / overhaul that could be done but this patch isn't that.

Bump the Identity api version to one that works

---

source/kubernetes.rst
source/kubernetes/_containers_assets/octavia-ing-configmap.yml
source/kubernetes/_containers_assets/octavia-ing-ingress.yml
source/kubernetes/_containers_assets/octavia-ing-rbac.yml
source/kubernetes/_containers_assets/octavia-ing-statefulset.yml
source/kubernetes/_containers_assets/storage_classes.yml
source/kubernetes/ingress.rst

Kubernetes

---

source/kubernetes.rst
source/kubernetes/versions.rst

Hi Bruno,
This document about versions is quite important for us, so I really need your comments here. Feel free to give me a call if there is anything unclear.

Add k8s versions

---

source/conf.py
source/identity-access-management/roles.rst
source/kubernetes/user-access.rst

WIP: Admonitions for roles on chrome & firefox

---

source/kubernetes/auto-healing.rst
source/kubernetes/versions.rst

1. Add 'how to support more node conditions' for auto healing
2. Clarification about addons version upgrade

Improve k8s doc

---

source/kubernetes/quickstart.rst
source/kubernetes/versions.rst

also fixed some grammar / spelling mistakes on the versions page. 
placed a note in quickstart about v1.20.x templates using containerd.

added notes about changes with v1.20.x tempaltes

---

source/getting-started/shared-responsibility-model.rst

Proposed re-write of the shared responsibility model text. Needs a spell check etc. :)

Rewrite shared model

---

source/getting-started/access.rst

Remove all allow-list references as we will no longer do that.
Mention rate limiting.

Clarify we rate limit and do not filter API calls (anymore)

---

source/images/importing-vms.rst

Makes clear we need virtio drivers and how to check for them

Document virtio stuff.

---

source/block-storage/_scripts/heat/create-attach-volume.yaml

change defaults to default - just for fun

change defaults to default - just for fun

---

source/object-storage.rst
source/object-storage/faq.rst
source/object-storage/software-configuration.rst

* Add documentation for Duplicati
* Move s3cmd

Client configuration for Object Storage

---

pre-commit
source/object-storage/advanced.rst
source/object-storage/faq.rst

Updated and expanded the section on generating a temporary URL to a swift object.
Added more details on determining the object path and added an example using python to generate the URL.

Updated the section on creating a temporary URL to a swift object

---

source/images/images-by-catalyst.rst

Fix up use of upper/lowercase for SUSE

---

source/alarm/overview.rst

Added an example of creating an alarm using the CLI as well as details of available meters, meter resolution and display alarm history.

Add alarm CLI example

---

source/images/images-by-catalyst.rst

Add documentation to help people register their SUSE SLES instances.

Add documentation for SUSE SLES images

---

source/alarm/overview.rst

Added descriptions for the ceilometer meters.

Improved the alarm meter list with descriptions.

---

source/database/create-database.rst

Remove whitespace introduced by Github editor

Remove whitespace introduced by Github editor

---

source/kubernetes/versions.rst

Update versions used to align more closely with currently available

Update Magnum Kubernetes internal documentation

---

source/compute/gpu-support.rst

Updated URLs to NVIDIA drivers and license

Updated URLs to NVIDIA drivers and license

---

source/release-notes.rst
source/release-notes/release_2023-02-23.rst

Note that I haven't used the release date, since that is behind when the release happened.

Added release notes for Burst Compute, GPU compute and nested virt

---

source/kubernetes/_containers_assets/octavia-ing-ingress.yml
source/kubernetes/ingress.rst

Ingress is feature state stable in k8s since 1.19.

Update K8s ingress documentation

---

source/image.rst
source/images/downloading-image.rst

After a customer asked about how to download an image I have written a brief how to.

Added page about downloading images from Glance.

---

source/orchestration/hot-format.rst

Based on my work for a customer, realized that the list of Heat resources we support needed updating

Updated the list of Heat resources that we support.

---

source/load-balancer/_scripts/layer4-files/cli-example.rst
source/load-balancer/layer-7.rst
source/object-storage/software-configuration.rst
source/object-storage/storage-access-control.rst
source/object-storage/tutorial-scripts/curl.rst
source/object-storage/tutorial-scripts/replication-api.rst

Add instructions for Cyberduck, S3 Browser and WinSCP.
I'm still working on a profile for Cyberduck that'll simplify configuration for Cyberduck, but it'd be good to get something out to point customers at.

Object storage improvements

---

source/first-instance/dashboard-windows.rst

Fix a compile error from a previous PR.

Trimmed trailing space in dashboard-windows.rst

---

source/getting-started/additional-information.rst

We are ISO 27001 certified in all regions.

Update ISO 27001 certification status on Additional Info

---

source/kubernetes.rst
source/kubernetes/auto-scaling.rst

* reinstate autoscaling in docs
* Add to TOC
* comment about node count

Reinstate auto-scaling docs

---

source/sdks-and-toolkits/linux-mac-cli.rst

Also added a comment about needing to use pipx in some circumstances instead of pip

Changed the version of the linux example in the cli install section 

---

source/compute/instance-types.rst

Incorporates fixes from comments on #526.
Expands on some details about vCPU execution that were left out before.

Reword resize, fix typos, expand vCPU explanation

---

requirements.txt
source/conf.py

because it isn't really suitable for our environment

Drop the use of sphinx-reredirects

---

source/database/create-database.rst
source/release-notes/release_2024-07-15.rst

A few fixes and improvements to the documentation for our database service.

Database updates

---

source/compute/gpu-support.rst
source/compute/launch-compute-instance.rst
source/compute/quickstart.rst
source/kubernetes.rst
source/kubernetes/clusters.rst
source/kubernetes/gpu-acceleration.rst
source/release-notes.rst
source/release-notes/release_2025-07-14.rst

Updates included:
* New C3-GPU flavor
* GPU support for CCKS (Kubernetes) worker nodes
* Various improvements to associated compute documentation

Add release notes for 14 July 2025
