catalyst-cloud/catalystcloud-docs

source/dashboard.rst
Volume-backed snapshots need to be booted with the correct (non-default) options in order for further bootable snapshots to be able to be created.
=> FAQ: nested snapshots

source/dashboard.rst
Updates the Dashboard page to reflect the changes made to allow
relatively unfettered access to Horizon, the OpenStack dashboard.
=> The dashboard is now open to the public Internet.

source/contributing.rst
The section title "Submiting a patch" is short one 't'.
This commit fixes that.
signed-off-by: Martin Millnert <martin@millnert.se>
=> Bugfix: Fix a very meta typo under Contribution

source/first-instance/overview.rst
Clarified that the creation of network/subnet/router are not required in a new tenancy as these are created by default.
Pointed out that these steps are included for completeness in case default networking has been deleted or an additional network is required.
=> clarified first instance, when networking steps need to be followed

source/tutorials/ansible-openstack-dynamic-inventory.rst
Fixed in shade:
commit c6017bdc80b6a0efdcff8202dd7d37e4155f3733
Author: Monty Taylor <mordred@inaugust.com>
Date:   Tue Apr 12 07:28:14 2016 -0500
Honor default_network for interface_ip
When we generate the interface_ip (which is used, amongst other things,
by ansible dynamic inventory) we do our best to figure out based on
config which of the IPs a server has should be the one that the user
wants to be "the" interface. In the previous patches, we added support
for the user configuring a "default_network" for one of their networks.
If the user has done this, and the server has an IP on that network, we
should use that network for interface_ip.
Change-Id: I440916622f9dfe12f8865bb1841dd0932d3cd7d0
=> remove Instance detection section as the issue has been fixed in shade

source/compute.rst, source/tutorials.rst, source/tutorials/deploying-a-turnkey-image.rst
Created a new tutorial detailing how to add a Turnkey Linux image to the Catalyst Cloud and create a new instance from it.
=> create new tutorial for Turnkey Linux images

source/object-storage.rst
update overview to include automatice geographic replication
=> remove references to ceph documentation for s3 apis

source/access-control.rst
This document used sentence case titles, except for in this one place. This commit fixes it.
=> Update access-control.rst to use title capitalisation consistent with other titles

source/image.rst
The default user in CoreOS images is "core", as opposed to "coreos".
=> Minor: the default CoreOS user is "core"

source/tutorials/deploying-highly-available-instances-with-keepalived.rst
Example includes the use of fixed IP addresses by default which accounts for this problem.
=> remove warning around neutron dhcp bug

source/load-balancer.rst
I've made a few minor changes to formatting/spelling/grammar.
I've also just added the explicit 'wait until the load balancer is active'
Creating the load balancer takes a while longer than the other operations and the error message that OpenSack gives is not clear.
```
Load Balancer e0e52288-d9a7-4cfa-89fe-862ac2b1f331 is immutable and cannot be updated. (HTTP 409) (Request-ID: req-99428a08-206e-4609-9858-d42a6d0791b3)
```
=> Minor fixes to loadbalancer documentation

playbooks/create-x-servers.yml, source/tutorials/compute/ansible-create-x-servers-using-in-memory-inventory.rst
The create-x-servers.yml playbook has been updated with native
YAML syntax, as this is considered best practice, rather than
inline module arguments.
The associated documentation page has also been updated to follow
the Catalyst Docs Style guide, with some minor edits.
=> Update Ansible example playbook and associated doc

source/kubernetes.rst
Now we're migrating to Fedora CoreOS driver with Podman and hyperkube,
on POR and HLZ regions, a cluster creation now takes 6-10 mins.
=> Remove the known issue of "15-25mins to create cluser"

source/release-notes.rst, source/release-notes/release_10_sept_2020.rst
New versions of Kubernetes are now referenced by the templates.
=> add release note for template updates

source/network/vpn.rst
=> Added warning about using the & character in the VPN PSK.  

autobuild_requirements.txt, requirements.txt
Github has removed support for unauthenticated git clone.
See:
https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Github has removed support for unauthenticated git protocol.

source/kubernetes/user-access.rst
- k8s_developer is a privileged account that can escalate
their own privileges, if not actively restrained.
- Provide solutions that can be used to restrain pods and
therefore restrain the k8s_developer role.
=> Adjust role descriptions to clarify k8s_developer

source/getting-started/access.rst, source/sdks-and-toolkits/apis.rst
Since the error code (429) wasn't mentioned, it was hard to find. Add it and also call out again we rate limit on the API page.
=> Add more hints about ratelimits

source/database/create-database.rst
Be explicit about the initial username length for each datastore type in DBaaS.
MySQL 5.7.8+ supports 32 character usernames, but DBaaS deployment mechanism is designed to support all versions of MySQL. MySQL <5.7.8 only supported 16 characters. This should be updated when support of only  MySQL >=5.7.8 is made.
=> Add database username length limit

source/compute/gpu-support.rst
Some changes to the URLs for drivers and licenses for GPU VMs were missed.
Tested the links after making sure the docs build too this time!
=> Fix links to GPU drivers/lic

source/images/uploading-image.rst
It was 500MB but is actually 5GB now.
=> Updated the limit on the warning about image uploads in the dashboard

source/tutorials/containers/deploying-a-hpc-slurm-cluster.rst, source/tutorials/other/region-failover-using-the-fastly-cdn.rst
Remove the link to the gc3.uzh.ch (Grid Computing Competence Center) as it no longer resolves.
Updated link to anchor on the fastly tutorial.
=> Fix two broken external links

source/block-storage/faq.rst, source/tutorials/containers/deploying-a-hpc-slurm-cluster.rst, source/tutorials/other/region-failover-using-the-fastly-cdn.rst
The header levels were incorrect on the FAQ section about resizing volumes: "Boot volumes" was at the same level as "How to grow a cinder volume?" when the former should have been a sub heading.
=> Block storage faq header levels

source/network/network-bp.rst
Remove reference to router HA under the networking best practice as it is no longer something we are going to do.
=> Remove reference the router HA.

source/database/create-database.rst, source/kubernetes/storage.rst
Clarify that the network in the customers project that the database instance is created in must have access to the internet.
Fix broken links that should have been internal and pointed to a section that have been rewritten
=> Database instances need a connection to the internet to creae

source/kubernetes/quickstart.rst
Remove the trailing `/` from the Kubernetes Dashboard link in the Quick Start guide.
Also, use IP addresses reserved for documentation use in the Quick Start.
=> Fix Kubernetes Dashboard link in Quick Start

source/kubernetes/appendix.rst
* Fix `b1.sr-r3-nvme-1000` formatting to use double backticks, as required for "code snippets" in RST.
* Consistent capitalisation of Control Plane and Worker nodes.
* Consistent wording for label accepted values / examples.
=> Minor formatting fixes to the Kubernetes Appendix

source/backups.rst, source/backups/duplicity.rst, source/kubernetes/clusters.rst, source/release-notes.rst, source/release-notes/release_2024-05-27.rst
Also:
* Fix links to duplicity
* Add autoscaler note back to clusters page.
=> Add backdated release notes for 1.29

source/identity-access-management/application-credentials.rst
Added warning that keystone will nuke a uses application credentials if a role on a project is removed.
=> Warning about applicaton credentials.

source/compute/faq.rst
Pedantically, we did mean bytes in this sentence, not bits. I have also checked for other occurances of Gb instead of GB and there are no others I could see.
=> Fix minor error using b (bits) and not B (bytes)

source/compute/gpu-support.rst
This is a minor terminology change, we provide vCPU and describe what vCPU means in other docs.
=> Change GPU flavours from "cores" to "vcpu", latter is more correct

source/compute/instance-types.rst
The discussion and notes on threading was less clear, prompted by c1a-gpu and c2a-gpu having SMT turned off. This also may be needed for theoretical c3-burst which may be on CPUs incapable of threading.
Also added c2a-gpu to tables of CPU features/policies.
=> Clarify threading and add c2a-gpu
